<a href="https://colab.research.google.com/github/duke2407/bmt/blob/main/21517_10%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [1]:
#1 Series 생성

s = pd.Series({1,3,5,np,nan,6,8})
s

NameError: ignored

In [3]:
df.iloc[1:3,[0,3]]

A         D
2020-11-14 -0.106887 -0.398889
2020-11-15 -1.939790  0.960197

In [4]:
import pandas as pd
import numpy as np

s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])

print(s.str.lower())

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object


In [ ]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 

In [2]:
import pandas as pd
import numpy as np

dates = pd.date_range('20201113', periods=6)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 
print(df.values)

[[ 2.02042433  0.18840161 -1.04403558 -0.38988295]
 [-0.10688747 -0.66846117  0.17165865 -0.39888916]
 [-1.93979041  0.63252311 -0.98434239  0.96019724]
 [-0.70431828 -1.26818761 -1.79659702 -0.44299217]
 [ 1.29058805 -0.8703711  -0.13156943  0.32302924]
 [ 1.46438654  1.30162292  0.35482261 -2.24136946]]


In [5]:
df.iloc[3,2]

-1.7965970235919229

In [6]:
import pandas as pd
import numpy as np

rng = pd.date_range('11/14/2020', periods=5, freq='M') 

ts = pd.Series(np.random.randn(len(rng)), rng)

print(ts);print()

ps = ts.to_period()
print(ps);print()

print(ps.to_timestamp())

2020-11-30    0.708304
2020-12-31   -1.053930
2021-01-31    0.250903
2021-02-28   -1.103636
2021-03-31    1.767440
Freq: M, dtype: float64

2020-11    0.708304
2020-12   -1.053930
2021-01    0.250903
2021-02   -1.103636
2021-03    1.767440
Freq: M, dtype: float64

2020-11-01    0.708304
2020-12-01   -1.053930
2021-01-01    0.250903
2021-02-01   -1.103636
2021-03-01    1.767440
Freq: MS, dtype: float64


In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        'A' : ['one', 'one', 'two', 'three'] * 3,
        'B' : ['A', 'B', 'C'] * 4,
        'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar' ] * 2,
        'D' : np.random.randn(12),
        'E' : np.random.randn(12)
    }
)

print(df);print()

pd.pivot_table(df, values = 'D', index = ['A', 'B'], columns = ['C'])

        A  B    C         D         E
0     one  A  foo -0.049223 -1.505597
1     one  B  foo -2.019913  0.697720
2     two  C  foo  0.720090 -1.106909
3   three  A  bar -0.858867 -0.899696
4     one  B  bar  0.862958  1.353117
5     one  C  bar -0.140255 -0.401530
6     two  A  foo  2.260833  0.850781
7   three  B  foo  0.067715  0.518728
8     one  C  foo  0.031991  1.593159
9     one  A  bar  2.007732  0.129957
10    two  B  bar  2.093978 -0.845041
11  three  C  bar -0.495051 -1.028667



C             bar       foo
A     B                    
one   A  2.007732 -0.049223
      B  0.862958 -2.019913
      C -0.140255  0.031991
three A -0.858867       NaN
      B       NaN  0.067715
      C -0.495051       NaN
two   A       NaN  2.260833
      B  2.093978       NaN
      C       NaN  0.720090

In [7]:
import pandas as pd
import numpy as np

rng = pd.date_range('11/14/2020', periods=5, freq='D')

ts = pd.Series(np.random.randn(len(rng)), rng)

print(ts);print()

ts_utc = ts.tz_localize('UTC') 
print(ts_utc);print()


ts_utc_us=ts_utc.tz_convert('Asia/Seoul') #
print(ts_utc_us);print()

2020-11-14    0.532826
2020-11-15    1.646647
2020-11-16    1.207124
2020-11-17    1.490031
2020-11-18   -0.420355
Freq: D, dtype: float64

2020-11-14 00:00:00+00:00    0.532826
2020-11-15 00:00:00+00:00    1.646647
2020-11-16 00:00:00+00:00    1.207124
2020-11-17 00:00:00+00:00    1.490031
2020-11-18 00:00:00+00:00   -0.420355
Freq: D, dtype: float64

2020-11-14 09:00:00+09:00    0.532826
2020-11-15 09:00:00+09:00    1.646647
2020-11-16 09:00:00+09:00    1.207124
2020-11-17 09:00:00+09:00    1.490031
2020-11-18 09:00:00+09:00   -0.420355
Freq: D, dtype: float64



In [8]:
import pandas as pd
import numpy as np

rng = pd.date_range('11/14/2020', periods=100, freq='S') 

ts = pd.Series(np.random.randint(0, 500, len(rng)), index = rng) 

print(ts.resample('5min').sum());print()


2020-11-14    24935
Freq: 5T, dtype: int64



In [11]:
[92] df.A > 0.5

SyntaxError: ignored

In [12]:
df2[E] \ [1,2,3,4,5,6]

SyntaxError: ignored

In [13]:
df.A

0       one
1       one
2       two
3     three
4       one
5       one
6       two
7     three
8       one
9       one
10      two
11    three
Name: A, dtype: object

In [14]:
df.A >0

TypeError: ignored